octomap_mapping_node:
  ros__parameters:
    octomap.resolution: 0.2
    octomap.prob_hit: 0.7
    octomap.prob_miss: 0.45
    octomap.occupancy_thresh: 0.5
    octomap.localmap_thresh: 1.0      # delete map if the occupied cells range is larger than this value
    octomap.pointcloudMaxX: 5.0
    octomap.pointcloudMinX: -4.0
    octomap.pointcloudMaxY: 1.5
    octomap.pointcloudMinY: -1.5
    octomap.pointcloudMaxZ: 1.5
    octomap.pointcloudMinZ: -1.5
    octomap.m_Expansion_range_x: 0.02  # Map expansion parameters in x
    octomap.m_Expansion_range_y: 0.02
    octomap.m_Expansion_range_z: 0.02
    octomap.m_isoccupiedThresh: 0.7    # Threshold for occupancy
    octomap.cloud_topic: /cloud_registered
    octomap.map_frame: world
    octomap.sensor_frame: ""
    octomap.tf_timeout: 0.1
    
